language: node_js
node_js:
before_install:
  - "curl https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | bash"
  - "source ~/.nvm/nvm.sh"
  - "nvm install iojs"
script:
  - "npm run prepublish"
  - "npm test"